<div class="login-container">

    <div class="brand">
        <h1>Arte&Cia</h1>
        <p>Painel Administrativo</p>
    </div>

    <!-- Exibir erro se login inválido -->
    <div id="error" class="error">Usuário ou senha inválidos</div>

    <form id="authentication-form">
        <label for="usuario">E-mail</label>
        <input type="email" name="usuario" id="usuario">

        <label for="senha">Senha</label>
        <input type="password" name="senha" id="senha">

        <button type="submit">Entrar</button>
    </form>


    <div class="footer">
        © Arte&Cia Limpeza do Lar
    </div>

</div>