<div class="container mt-5 pt-5">
    <div class="row justify-content-center align-items-center mt-3">
        <div class="col-md-8">
            <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Formulário de Envio</h3>
                    <p>Deseja solicitar um orçamento? <a href="/agendamento" class="link-primary text-decoration-none">Clique aqui</a></p>
                    <form id="form-recrutamento">
                        <div class="mb-3">
                            <label for="nome" class="form-label fw-bolder">Nome Completo</label>
                            <input type="text" class="form-control" id="nome" name="nome" placeholder="Informe seu nome completo">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label fw-bolder">E-mail</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Informe seu email" >
                        </div>
                        <div class="mb-3">
                            <label for="contato" class="form-label fw-bolder">Telefone/Whatsapp</label>
                            <input type="tel" class="form-control" id="contato" name="contato" placeholder="(99) 99999-9999" >
                        </div>
                        <div class="mb-3">
                            <label for="curriculo" class="form-label fw-bolder">Currículo (PDF, DOC, DOCX)</label>
                            <input type="file" class="form-control" id="curriculo" name="curriculo" accept=".pdf,.doc,.docx">
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Enviar Currículo</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

