<div class="container-post">
    <h2>Nova Categoria</h2>

    <form method="POST" action="/categorias/salvar" class="form-post">
        <div class="form-group">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome">
        </div>

        <div class="form-group">
            <label for="slug" class="form-label">Slug</label>
            <input type="text" class="form-control" id="slug" name="slug">
        </div>

        <div class="form-check form-check-inline mt-2">
            <input class="form-check-input" type="radio" name="status" id="status" value="1">
            <label class="form-check-label" for="ativo">
                Ativo
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="status" value="0">
            <label class="form-check-label" for="inativo">
                Inativo
            </label>
        </div>
        <div class="mt-3">
            <a href="/categorias" class="btn btn-secondary">Cancelar</a>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>

    </form>
</div>