<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8" />
<title>Login | Admin Arte&Cia</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/public/resources/css/admin.css" />
<link rel="shortcut icon" href="/public/resources/img/favicon/android-chrome-512x512.png" type="image/x-icon">
<meta name="author" content="Paulo Rodrigo dos Santos">
<meta name="owner" content="Arte&Cia Limpeza do Lar">
<meta name="copyright" content="© 2025 Arte&Cia Limpeza do Lar">
<script type="application/ld+json">
{
  "@context": "https://www.arteecialimpezadolar.com.br",
  "@type": "Organization",
  "name": "Arte&Cia Limpeza do Lar",
  "url": "https://www.arteecialimpezadolar.com.br",
  "founder": "Paulo Rodrigo dos Santos"
}
</script>
</head>
    <body>
        <?= $this->content() ?>
    </body>
    <script type="module" src="/public/resources/js/authenticator.js"></script>
</html>