<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <title>Admin | Arte&Cia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="/public/resources/img/favicon/android-chrome-512x512.png" type="image/x-icon">
  <link rel="stylesheet" href="/public/resources/css/dashboard.css" />
</head>

<body>
  <header class="">
    <aside>
      <?php $urlAtual = $_SERVER['REQUEST_URI']; ?>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid px-5">
          <a class="navbar-brand" href="#">Arte&Cia | <span class="fs-6 text">Painel Administrativo</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
             <div class="d-flex">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
         
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link <?php echo ($urlAtual == '/dashboard') ? 'active' : ''; ?>" aria-current="page" href="#">Dashboard</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle <?php echo ($urlAtual == '/post') ? 'active' : ''; ?>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Postagens
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/post">Listar</a></li>
                    <li><a class="dropdown-item" href="/post/novo-post">Cadastrar</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle <?php echo ($urlAtual == '/categorias') ? 'active' : ''; ?>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categorias
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/categorias">Listar</a></li>
                    <li><a class="dropdown-item" href="/categorias/nova-categoria">Cadastrar</a></li>
                  </ul>
                  </li>
              </ul>

            </div>
          </div>
        </div>
      </nav>
    </aside>
  </header>

  <main class="container-fluid px-5">
    <?= $this->content() ?>
  </main>

  <!-- Modais de erro e sucesso -->
  <div id="errorModal" class="errorModal"><span id="errorModalMessage"></span></div>
  <div id="showSuccessModal" class="showSuccessModal"><span id="successModalMessage"></span></div>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <!-- Scripts personalizados -->
  <script type="module" src="/public/resources/js/posts.js"></script>
  <script type="module" src="/public/resources/js/categorias.js"></script>

</body>

</html>