<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8" />
  <title>Admin | Arte&Cia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/public/resources/css/dashboard.css" />
  <link rel="shortcut icon" href="/public/resources/img/favicon/android-chrome-512x512.png" type="image/x-icon">
</head>
<body>
    <aside>
    <h1>Arte&Cia</h1>
    <nav>
      <a href="#">Dashboard</a>
      <a href="#">Posts</a>
      <a href="#">Serviços</a>
      <a href="#">Orçamentos</a>
      <a href="#">Configurações</a>
      <a href="/admin-logout">Sair</a>
    </nav>
  </aside>
     <?= $this->content() ?>
</body>
</html>
