<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <title>Admin | Arte&Cia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="/public/resources/img/favicon/android-chrome-512x512.png" type="image/x-icon">
</head>

<body>
  <header class="container-fluid">
    <aside>
      <?php $urlAtual = $_SERVER['REQUEST_URI']; ?>
      <h1>Arte&Cia</h1>
      <nav>
        <a href="/post" class="<?php echo ($urlAtual == '/dashboard') ? 'active' : ''; ?>">Postagens</a>
        <a href="/categorias" class="<?php echo ($urlAtual == '/categorias' || $urlAtual == '/categorias/criar') ? 'active' : ''; ?>">Categorias</a>
        <a href="#">Configurações</a>
        <a href="/admin-logout">Sair</a>
      </nav>
    </aside>
  </header>

  <main class="container">
    <?= $this->content() ?>
  </main>

  <!-- Modais de erro e sucesso -->
  <div id="errorModal" class="errorModal"><span id="errorModalMessage"></span></div>
  <div id="showSuccessModal" class="showSuccessModal"><span id="successModalMessage"></span></div>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <!-- Scripts personalizados -->
  <script type="module" src="/public/resources/js/posts.js"></script>
  <script type="module" src="/public/resources/js/categorias.js"></script>

</body>

</html>