<section id="home" class="caixa">
    <div class="container-fluid align-self-center mt-5">
        <div class="row">
            <div class="col-md-12 capa">
                <div id="carousel-spotify" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <h1 class="display-1 text-white text-shadow fw-bold">Sua casa merece o melhor!</h1>
                            <a href="/agendamento" class="btn btn-lg btn-custom btn-roxo">
                                Clique aqui e garanta sua limpeza!
                            </a>
                            <a href="/agendamento" class="btn btn-lg btn-custom btn-branco">
                                Saiba mais sobre nossos serviços
                            </a>
                        </div>
                        <div class="carousel-item">
                            <h1 class="display-1 text-white text-shadow fw-bold">Brilho e organização, sempre.</h1>
                            <a href="/agendamento" class="btn btn-lg btn-custom btn-branco">
                                Não perca mais tempo com a limpeza. Contrate já!
                            </a>
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carousel-spotify"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carousel-spotify"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>

            </div>
        </div>
    </div>
</section>
<section id="servicos" class="caixa">
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-6 p-3">
                <h2 class="mb-2 text-center">Quais são os Nossos Serviços?</h2>
                <div class="caixa-selecao">
                    <h3>Diarista</h3>
                    <h3>Faxineira</h3>
                    <h3>Passadeira</h3>
                    <h3>Limpeza Diária</h3>
                    <h3>Limpeza Comercial</h3>
                    <h3>Limpeza Doméstica</h3>
                </div>
                <p class="text-center">
                    <a href="/agendamento" class="btn btn-lg btn-custom btn-verde">Agende Sua Limpeza </a>
                </p>
            </div>
            <div class="col-md-6">
                <div class="row albuns">
                    <div class="col-md-6 icons">
                        <img src="/public/resources/img/site/varrendo-pessoa(1).jpg" alt="Faxineira varrendo a casa" class="img-fluid">
                    </div>
                    <div class="col-md-6 icons">
                        <img src="/public/resources/img/site/passando-roupa-pessoa.jpg" alt="Passadeira" class="img-fluid">
                    </div>
                </div>
                <div class="row albuns">
                    <div class="col-md-6 icons">
                        <img src="/public/resources/img/site/limpando-banheiro-pessoa.jpg" alt="Faxineira limpando o banheiro" class="img-fluid">
                    </div>
                    <div class="col-md-6 icons">
                        <img src="/public/resources/img/site/lavando-louca-pessoa.jpg" alt="Faxineira limpando a cozinha" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="recursos" class="caixa">
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-6">
                <img src="/public/resources/img/site/limpando-casa.jpg" alt="Faxineira limpando os vidros" class="img-fluid">
            </div>
            <div class="col-md-6  mt-5 text-center">
                <h2 class="text-center mb-3">Sobre Nós</h2>
                <div>
                    <p>
                        A Arte & Cia Limpeza do Lar oferece soluções flexíveis e personalizadas para sua casa. Seja para uma limpeza semanal, uma faxina completa ou um cuidado especial, nossos parceiros estão prontos para atender suas necessidades.
                    </p>
                    <p>
                        Desfrute de mais tempo livre e de um ambiente sempre agradável. E o melhor: agendar seu serviço é rápido e fácil, leva apenas alguns cliques!
                    </p>
                </div>
                <div class="">
                    <p>
                        Sua casa limpa do seu jeito.
                    </p>

                    <a href="/agendamento" class="btn btn-lg btn-custom btn-amarelo">
                        Agendar agora
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>