<div class="container mt-5 pt-5">
    <div class="row justify-content-center align-items-center mt-5">
        <div class="col-md-8">
            <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                <div class="card-body text-center ">
                    <h3 class="card-title text-center mb-4">Currículo enviado com sucesso!</h3>
                   <p>Agradecemos seu interesse. Assim que possível entraremos em contato.</p>
                    <a href="/">Voltar para a página inicial</a>
                </div>
            </div>
        </div>
    </div>
</div>