    <div class="row my-3">
      <div class="col-md-4">
        <div class="card p-3">
          <h5 class="card-title">
            Posts publicados
          </h5>
          <p class="card-text">
              <?= $this->view->totalPosts ?>
          </p>        
        </div>
      </div>
      <div class="col-md-4">
        <div class="card p-3">
          <h5 class="card-title">
            Rascunhos
          </h5>
          <p class="card-text">
             <?= $this->view->totalRascunhos ?>
          </p>        
        </div>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Status</th>
          <th>Data</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->view->postsRecentes as $post): ?>
          <tr>
            <td><?= htmlspecialchars($post['titulo']) ?></td>
            <td>
              <?php echo ucfirst($post['status']); ?>
            </td>
            <td><?= date('d/m/Y', strtotime($post['created_at'])) ?></td>
            <td class="actions">
              <a href="/post/editar?id=<?= $post['id'] ?>">Editar</a>
              <a href="/post/deletar?id=<?= $post['id'] ?>">Excluir</a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>