    <div class="row my-3">
      <div class="col-md-4">
        <div class="card p-3">
          <h5 class="card-title">
            Posts publicados
          </h5>
          <p class="card-text">
              <?= $this->view->totalPosts ?>
          </p>        
        </div>
      </div>
      <div class="col-md-4">
        <div class="card p-3">
          <h5 class="card-title">
            Rascunhos
          </h5>
          <p class="card-text">
             <?= $this->view->totalRascunhos ?>
          </p>        
        </div>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Categoria</th>
          <th>Status</th>
          <th>Destaque Principal</th>
          <th>Destaque Categoria</th>
          <th>Data de Criação</th>
          <th>Data de Atualização</th>
          <th colspan="">Ações</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->view->postsRecentes as $post): ?>
          <tr>
            <td> <a href="/post/editar?id=<?= $post['id'] ?>" class="text-decoration-none"><?= htmlspecialchars($post['titulo']) ?></a></td>
            <td> <?php echo ucfirst($post['categoria_nome']); ?></td>
            <td>
              <?php echo ucfirst($post['status']); ?>
            </td>
            <td> <?php echo $post['destaque_principal']; ?></td>
            <td> <?php echo $post['destaque_categoria']; ?></td>
            <td><?= date('d/m/Y', strtotime($post['created_at'])) ?></td>
            <td><?= date('d/m/Y', strtotime($post['updated_at'])) ?></td>
            <td>
              <a href="/post/deletar?id=<?= $post['id'] ?>"><i class="fa-solid fa-trash-can"></i></a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>