  <main>
    <header>
      <h2>Postagens</h2>
      <div class="user">Olá, Admin</div>
    </header>

    <section class="grid">
        <a href="/post/novo-post" class="btn btn-primary">Nova Postagem</a>
      <div class="card">
        <h3>Posts publicados</h3>
        <strong><?= $this->view->totalPosts ?></strong>
      </div>
      <div class="card">
        <h3>Rascunhos</h3>
        <strong><?= $this->view->totalRascunhos ?></strong>
      </div>
    </section>
      
    <table class="table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Status</th>
          <th>Data</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->view->postsRecentes as $post): ?>
        <tr>
          <td><?= htmlspecialchars($post['titulo']) ?></td>
          <td>
            <?php  echo ucfirst($post['status']); ?>
          </td>
          <td><?= date('d/m/Y', strtotime($post['created_at'])) ?></td>
          <td class="actions">
            <a href="/post/editar?id=<?= $post['id']?>">Editar</a>
            <a href="#">Excluir</a>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>

  </main>
