<!Doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="/public/resources/img/favicon/android-chrome-512x512.png" type="image/x-icon">
    <link rel="stylesheet" href="/public/resources/css/style3.css">
    <title>Arte & Cia - Limpeza do Lar</title>
</head>

<body>
    <header class="">
        <nav class="navbar navbar-light fixed-top navbar-transparente">
            <div class="container-fluid row ">
                <div class="col-4 d-flex align-items-center">
                    <a style="text-decoration: none;" class="navbar-toggler" data-bs-toggle="offcanvas" data-bs-target="#menuLateral" aria-controls="menuLateral" aria-label="Abrir menu">
                        <i class="fas fa-bars text-white"></i>
                        <span class="ms-1" style="text-transform: uppercase; color:white; font-weight: bold; font-size:0.8em">menu</span>
                    </a>
                </div>

                <div class="logo my-2 col-4 d-flex justify-content-center align-items-center">
                    <a class="navbar-brand text-white" href="/blog">
                        <img src="/public/resources/img/logo.png" alt="" width="110">
                    </a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <form action="/buscar" method="get">
                        <div class="input-group" style="max-width: 250px;">
                            <input type="search" class="form-control rounded-start-pill" name="s" placeholder="Buscar..." aria-label="Buscar" style="background: rgba(255,255,255,1); border: none; color: #333; font-size: 0.95em;">
                            <button class="btn btn-outline-light rounded-end-pill" type="submit" aria-label="Buscar">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>

        <!-- Menu lateral -->
        <div class="offcanvas offcanvas-start offcanvas-transparente" tabindex="-1" id="menuLateral" aria-labelledby="menuLateralLabel"  data-bs-backdrop="false">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title text-white" id="menuLateralLabel"></h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Fechar"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="/blog" class="nav-link text-white">Início</a></li>
                    <?php foreach($this->view->categorias as $indice => $categorias) { ?>
                    <li class="nav-item mb-2"><a href="\blog?categoria=<?= $categorias['slug']?>" class="nav-link text-white"><?= $categorias['nome'] ?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </header>
        <main class="top-5 mt-5 pt-4">
        <?= $this->content() ?>
        </main>
    <footer class="">
        <div id="errorModal" class="errorModal">
            <span id="errorModalMessage"></span>
        </div>
        <div id="showSuccessModal" class="showSuccessModal">
            <span id="successModalMessage"></span>
        </div>
        <div class="container-fluid text-white ps-5">
            <div class="row">
                <div class="col-lg-8 col-md-6 col-sm-6 d-flex list-unstyled mb-3">
                    <img src="/public/resources/img/site/Logo.png" width="100" height="80" alt="" class="pt-2">
                    <ul class="navbar-nav ms-2">
                        <li class="nav-item"><a href="/#recursos" class="nav-link">Conheça a Arte&Cia</a></li>
                        <li class="nav-item"><a href="/#servicos" class="nav-link">Nossos Serviços</a></li>
                        <li class="nav-item"><a href="/agendamento" class="nav-link">Quero uma Limpeza</a></li>
                        <li class="nav-item"><a href="/recrutamento" class="nav-link">Quero Prestar Serviços</a></li>
                        <li class="nav-item"><a class="nav-link" href="/blog">Blog Arte&Cia</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 ">
                    <ul class="midias-sociais d-flex list-unstyled text-center justify-content-center pt-3">
                        <li class="me-3">
                            <a href="https://www.facebook.com/arteecialimpezadolar" target="_blank"><img src="/public/resources/img/site/facebook.png" alt="" class="img-fluid"></a>
                        </li>
                        <li class="me-3">
                            <a href="https://www.instagram.com/artecialimpezadolar/" target="_blank"><img src="/public/resources/img/site/instagram.png" alt="" class="img-fluid"></a>
                        </li>
                        <li class="me-3">
                            <a href="https://wa.me/5579999311107?text=Olá%2C%20gostaria%20de%20saber%20mais%20sobre%20os%20serviços%20de%20limpeza." target="_blank">
                                <img src="/public/resources/img/site/whatsapp.png" alt="WhatsApp" class="img-fluid">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="mb-0 small">
                        Arte & Cia - Limpeza do Lar © 2025. Todos os direitos reservados. <br>
                        Desenvolvido por <strong>PR</strong>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="module" src="/public/resources/js/agendamento.js"></script>
    <script type="module" src="/public/resources/js/recrutamento.js"></script>
</body>

</html>