<!Doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="img/favicon/android-chrome-512x512.png" type="image/x-icon">
    <link
        rel="stylesheet"
        type="text/css"
        href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.1/src/regular/style.css" />
    <link
        rel="stylesheet"
        type="text/css"
        href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.1/src/fill/style.css" />
    <link rel="stylesheet" href="css/style.css">

    <title>Arte & Cia - Limpeza do Lar</title>
</head>

<body>
    <header class="cabecalho">
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-transparente">
            <div class="container">
                <div class="logo">
                    <a class="navbar-brand text-white ms-md-5" href="/">
                        <img src="img/site/Logo.png" alt="" width="110">
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="ph ph-list"></i>
                </button>
                <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                    <ul class="navbar-nav ms-auto d-md-flex align-items-md-center ">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/#home">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#servicos"> Serviços </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#recursos">Como funciona</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link" href="/#recursos">Profissionais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#recursos">Conheça a Arte&Cia </a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" target="_blank" href="/blog"> Contato </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="/blog"> Blog </a>
                        </li>
                        <li class="ms-md-3 nav-item">
                            <a class="btn btn-sm btn-warning" href="/agendamento">Acessar conta <i class="ph ph-user"></i></a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <?= $this->content() ?>
    </main>
    <footer class="">
        <div class="container-fluid text-white ps-5">
            <div class="row ">
                <div class="col-lg-8 col-md-6 col-sm-6 d-flex list-unstyled  mb-3">
                    <img src="img/site/Logo.png" width="100" height="80" alt="" class="pt-2">
                    <ul class="navbar-nav ms-2">
                        <li class="nav-item"><a href="/#recursos" class="nav-link">Conheça a Arte&Cia</a></li>
                        <li class="nav-item"><a href="/#servicos" class="nav-link">Nossos Serviços</a></li>
                        <li class="nav-item"><a href="/agendamento" class="nav-link">Quero uma Limpeza</a></li>
                        <li class="nav-item"><a href="/recrutamento" class="nav-link">Quero Prestar Serviços</a></li>
                        <li class="nav-item"><a class="nav-link" href="/blog">Blog Arte&Cia</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 ">
                    <ul class="midias-sociais d-flex list-unstyled text-center justify-content-center pt-3">
                        <li class="me-3">
                            <a href="https://www.facebook.com/arteecialimpezadolar" target="_blank"><img src="img/site/facebook.png"></a>
                        </li>
                        <li class="me-3">
                            <a href="https://www.instagram.com/artecialimpezadolar/" target="_blank"><img src="img/site/instagram.png" alt="" class="img-fluid"></a>
                        </li>
                        <li class="me-3">
                            <a href="https://wa.me/5579999311107?text=Olá%2C%20gostaria%20de%20saber%20mais%20sobre%20os%20serviços%20de%20limpeza." target="_blank">
                                <img src="img/site/whatsapp.png" alt="WhatsApp" class="img-fluid">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="mb-0 small">
                        Arte & Cia - Limpeza do Lar © 2025. Todos os direitos reservados. <br>
                        Desenvolvido por <strong><a href="http://www.linkedin.com/in/paulorodrigodev" target="_blank" rel="noopener noreferrer"></a> PR </strong>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Modais de erro e sucesso -->
    <div id="errorModal" class="errorModal"><span id="errorModalMessage"></span></div>
    <div id="showSuccessModal" class="showSuccessModal"><span id="successModalMessage"></span></div>
    <!-- Scripts Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Scripts personalizados -->
     <script type="module" src="js/js.js"></script>
</body>

</html>